### ISSUE TITLE
TypeError: event.originalEvent.dataTransfer.files[0] is undefined

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#272] opened 2017-07-21 00:57 UTC
Found on https://send.dev.mozaws.net/__version__ (8d41907):

```js
{
  commit: "8d41907",
  source: "https://github.com/mozilla/send/",
  version: "0.1.2"
}
```

---

This is the companion bug to #271, which I can reproduce on Firefox (Beta).

### Steps to reproduce:
1. Go to https://send.dev.mozaws.net/
2. Drag and drop the Upload icon in the drop zone.

### Actual results:

<img width="1440" alt="firefox_send" src="https://user-images.githubusercontent.com/557895/28444832-c216b4b6-6d74-11e7-9f15-4978c2568337.png">

```
TypeError: event.originalEvent.dataTransfer.files[0] is undefined  bundle.js:1:9401
	onUpload https://send.dev.mozaws.net/bundle.js:1:9401
	dispatch https://send.dev.mozaws.net/bundle.js:1:95089
	add/elemData.handle https://send.dev.mozaws.net/bundle.js:1:91840
```

**Comment by pdehaan** [comment] 2017-07-21 01:14
This also happens if you try and drag the lock icon from the address bar into the drop zone.

**Comment by pdehaan** [comment] 2017-07-21 01:15
... or if I try and drag text from Sublime Text into the drop zone.

**Comment by wresuolc** [comment] 2017-07-21 15:55
Closing as a dupe of #275

**Closed by wresuolc** 2017-07-21 15:55 UTC
