### ISSUE TITLE
Links must have discernible text

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#442] opened 2017-08-04 20:30 UTC
via #139 

```
line 112  col 7   Error  Links must have discernible text                       axe
line 120  col 7   Error  Links must have discernible text                       axe
line 121  col 7   Error  Links must have discernible text                       axe
```

Not sure what these alleged errors are, or how legit this is.
I have a suspicion that they are either icon links (Mozilla, GitHub, Twitter), or possibly links with localized strings injected at runtime using l20n.

**Comment by inondle** [comment] 2017-10-11 16:44
I'd like to look into this.

**Comment by ericawright** [comment] 2017-10-11 16:47
thanks @inondle

**Comment by inondle** [comment] 2017-10-22 02:18
I'm unable to reproduce the "Links must have discernible text" error on https://send.dev.mozaws.net/ or https://fileshare.stage.mozaws.net. Is anyone else still getting those errors using the sonar tool?

**Comment by wresuolc** [comment] 2018-01-22 18:47
Closing.  Please re-open if it's reproducible.

**Closed by wresuolc** 2018-01-22 18:47 UTC
Labels: good first issue, skill:html
