### ISSUE TITLE
Using on Firefox focus crashes/doesn't work

### ISSUE THREAD

**Issue by jonathanGB** [mozilla/send#494] opened 2017-08-10 04:28 UTC
I uploaded a simple image (1.4MB) using Chrome for Android and downloaded it without problem.

However, when I tried on Firefox Focus:
1. I couldn't upload a file (upload button did nothing)
2. Downloading it on mobile would crash - oddly, the file was corrupted into a `.bin` file.

<img style="float: right" src="https://user-images.githubusercontent.com/8869660/29154431-7c1baa7c-7d49-11e7-8ca8-f25e1a74d3ea.png" width="300" />

**Comment by dannycoates** [comment] 2017-08-10 22:29
Thanks for the report! We are able to reproduce it. Unfortunately we don't know of an easy solution, so this will take some time to fix.

**Comment by jonathanGB** [comment] 2017-08-11 01:40
ok! Do you have an idea of what is the root of the problem though?

**Comment by dannycoates** [comment] 2017-08-11 18:14
https://github.com/mozilla-mobile/focus-android/issues/937

**Comment by wresuolc** [comment] 2017-08-16 17:46
thanks for finding the root cause. closing this

**Closed by wresuolc** 2017-08-16 17:46 UTC
