### ISSUE TITLE
add <meta> tags to support twitter cards

### ISSUE THREAD

**Issue by wanderview** [mozilla/send#370] opened 2017-08-01 14:29 UTC
I tweeted about send.firefox.com today:

https://twitter.com/wanderview/status/892391157086527489

And I noticed it doesn't generate any kind of twitter card.  It might be nice to provide some kind of logo or something.  (Obviously a preview of the payload would probably be bad...)

**Comment by SoftVision-PaulOiegas** [comment] 2017-08-01 15:28
In the mean time you can tweet the Test Pilot experiment link. That one generates one.

**Comment by pdehaan** [comment] 2017-08-01 15:35
Duplicate of #153; _"Add OpenGraph and Twitter Card metadata to pages"_

**Closed** 2017-08-01 15:49 UTC
