### ISSUE TITLE
Password option to allow sharing link over unencrypted networks

### ISSUE THREAD

**Issue by danielquinn** [mozilla/send#384] opened 2017-08-02 09:12 UTC
The trouble with sharing files like this is that the link will almost certainly be shared over an unencrypted system like email, effectively defeating all of the encryption you've done here.  Having an option to require a password to get the file would help with this (assuming of course that the user doesn't share the password over the same insecure channel, but you can't help everybody ;-))

FWIW I have a crude implementation of this in my little [Korra](https://github.com/danielquinn/korra) project.  Working instance is [here](https://transfer.danielquinn.org/).

**Comment by pdehaan** [comment] 2017-08-02 15:39
Duplicate of #381.

@danielquinn I moved your comment into that issue. 👍

**Closed by pdehaan** 2017-08-02 15:39 UTC
