### ISSUE TITLE
Uncaught TypeError: Cannot read property 'size' of undefined

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#271] opened 2017-07-21 00:53 UTC
Found on https://send.dev.mozaws.net/__version__ (8d41907):

```js
{
  commit: "8d41907",
  source: "https://github.com/mozilla/send/",
  version: "0.1.2"
}
```

---

Prepare to be underwhelmed...
I was only able to reproduce this in Chrome. Firefox gives a different error, so I'll file separately (ref: #272).

### Steps to reproduce:
1. Go to https://send.dev.mozaws.net/
2. Drag and drop the Upload icon in the drop zone.

### Actual results:

<img width="1440" alt="firefox_send" src="https://user-images.githubusercontent.com/557895/28444697-ec58d4f8-6d73-11e7-912f-b475684dfc28.png">

```
Uncaught TypeError: Cannot read property 'size' of undefined
    at HTMLBodyElement.onUpload (bundle.js:1)
    at HTMLBodyElement.dispatch (bundle.js:1)
    at HTMLBodyElement.elemData.handle (bundle.js:1)
onUpload  @ bundle.js:1
dispatch  @ bundle.js:1
elemData.handle @ bundle.js:1
```

Not sure if we have sourcemap support, but it may be useful in debugging.

**Comment by pdehaan** [comment] 2017-07-21 01:12
This happens in other cases too, like trying to drag that "secure" text from the Chrome address bar into the drop zone.

**Comment by wresuolc** [comment] 2017-07-21 15:56
duplicate of #275

**Closed by wresuolc** 2017-07-21 15:56 UTC
