### ISSUE TITLE
The text caret is wrongly displayed inside the field after adding the password using the "Enter" key

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/send#776] opened 2018-02-28 14:45 UTC
[Affected versions]:
- Firefox 58.0.2 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Start Firefox browser and navigate to "https://send.stage.mozaws.net/" page.
2. Upload a file and click the "Require a password to download this file" checkbox.
3. Type something in the password field and press "Enter".
4. Observe the password field.

[Expected result]:
- The password field is not focused.

[Actual results]:
- The password field is focused and the text caret is displayed inside it.

[Notes]:
- This issue is also reproducible on https://send.dev.mozaws.net.
- Attached a screen recording of the issue:

![caret remains displayed](https://user-images.githubusercontent.com/26000308/36793538-53d408b4-1ca6-11e8-833b-43114fdeddb4.gif)

**Comment by PunkChameleon** [comment] 2018-05-06 01:08
I am unable to reproduce this -- has this been fixed?

**Comment by SoftVision-CosminMuntean** [comment] 2018-05-07 15:33
@PunkChameleon I can still reproduce the issue following the provided STR on latest Firefox (59.0.3) release and latest Nightly (61..0a1) build. Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
The issue is reproducible on Send dev, stage and production server. 

@PunkChameleon on which version of Firefox and also on what OS did you test this issue?

**Comment by dannycoates** [comment] 2019-01-03 21:19
old (wontfix)

**Closed by dannycoates** 2019-01-03 21:19 UTC
Labels: [QA]:Minor issue, bug
