### ISSUE TITLE
The "Send another file" link on the error webpage can't be clicked

### ISSUE THREAD

**Issue by clement-lefevre** [mozilla/send#517] opened 2017-08-16 07:52 UTC
Reproduce everytime on Firefox Android:
- Remove the storage permission to Firefox to cause send.firefox.com to fail
- You get the "Something went wrong!" webpage
- The send another file under the image can't be clicked at all

**Comment by clement-lefevre** [comment] 2017-08-16 08:43
![Screenshot of the link](https://user-images.githubusercontent.com/1701721/29354990-9d091866-826f-11e7-9c39-1691d805cd6b.png)

**Comment by dannycoates** [comment] 2017-08-16 17:27
Thanks for the report :)

I think this is a duplicate of #478 and will be fixed in the next release

**Closed by dannycoates** 2017-08-16 17:27 UTC
