### ISSUE TITLE
High memory usage while a large file (~1GB) is encrypted

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#691] opened 2017-12-29 14:18 UTC
[Notes]:
- If you have a machine with 4 GB RAM the computer freeze while the file is encrypting. I have tested this using a iMac with 4 GB RAM and after the file started to be encrypted the system froze.
- For the first upload in a new Firefox session, the memory usage stabilizes when the upload reaches ~15-30%.
- For next uploads in the same Firefox session, the memory usage stabilizes when the upload reaches ~5-10%.

[Affected versions]:
- Firefox 57.0 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The Task Manager is opened. 

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.firefox.com/" page.
2. Upload a large file >1 GB.
3. Observe the Firefox memory usage in Task Manager when the file is encrypting.

[Expected result]:
- The memory usage goes up by at least the size of the file.

[Actual results]:
- The memory usage goes up by ~ 3 times higher than the size of the file.

[Additional Notes]:
- Here is a screen recording with the issue:
![high memmory](https://user-images.githubusercontent.com/19226534/34439037-d3b6eb14-ecb3-11e7-8498-70e93816af9d.gif)

**Comment by shikhar-scs** [comment] 2018-01-04 04:02
As a user I would suggest that we remove the option of uploading files > ~ 1-1.5 GB because it always freezes the system. 
Moreover @SoftVision-CosminMuntean  you have mentioned a cause [here](https://github.com/mozilla/send/issues/578#issuecomment-354993486) but my system's RAM is ~6GB. So its not advisable that we anyhow enable the ability to upload such large files.

At PR #695  I have introduced code which automatically cancels file uploads > 2GB after giving them a warning for about 4seconds . Thus, if we really need to introduce uploads >1 GB we can, say, display the warning and then maybe give an option to cancel (rather than mandatorily cancelling it ). Because freezing the machine of the user  (which generally has RAM of approx 4~8 GB) is not an advisable. 

(If the mentors agree ) I can work on this as it is very similar to #695.

**Comment by shikhar-scs** [comment] 2018-01-10 16:31
Any thoughts on this @SoftVision-CosminMuntean ?

**Comment by SoftVision-CosminMuntean** [comment] 2018-01-11 10:11
We already have a message displayed in the drop area which suggests that you upload files under 1GB for the most reliable operation:
`For the most reliable operation, it’s best to keep your file under 1GB.`

In my opinion we should not restrict uploading files between 1 and 2 GB since there are also users that have better systems and the issue is no reproducible for them.
But, we should also wait for an opinion from @johngruen or @dannycoates.

**Comment by shikhar-scs** [comment] 2018-01-11 10:21
@SoftVision-CosminMuntean Yep that's true. However, my opinion was meant for the general users 
> machine of the user (which generally has RAM of approx 4~8 GB)

I guess some more stricter warning would do. 
So yeah lets wait for the mentors' advice.

**Comment by dannycoates** [comment] 2019-01-03 21:13
fixed in vnext

**Closed by dannycoates** 2019-01-03 21:13 UTC

**Comment by Softvision-AndreeaCupsa** [comment] 2019-01-04 12:30
I have verified this issue and is no longer reproducible on "https://send2.dev.lcip.org" on Windows 10 x64, Arch Linux 4.14.3, and Mac 10.13.3.
