### ISSUE TITLE
Add a "report an issue" link to the webpage

### ISSUE THREAD

**Issue by clement-lefevre** [mozilla/send#518] opened 2017-08-16 07:57 UTC
As someone suggested on IRC, add a link to report  an issue on send.firefox.com would be nice.
Actually as a regular Mozilla contributor, I didn't knew if bugs were to be reported here or on Bugzilla until someone told me.

**Comment by wresuolc** [comment] 2017-08-16 17:40
There is a Feedback link that goes to the survey currently.  Marking needs:product

**Comment by ehuggett** [comment] 2017-08-22 15:34
Would this also allow malicious content to be reported? (I will move this to a separate issue if not)

I propose that a user should be able to report ('claim') that a link they have received violates Sends terms of service, specifically targeting attempts to abuse the service Send offers.

### 'standard' report
1. Should not contain any metadata or plaintext the server did not already posses/have logged.
1.1 The ID from the Send url should be sufficient?
1.2 This possibly makes it unnecessary to prompt for confirmation as this data is not sensitive, but it may be desirable to prevent accidental reports
1.3 May cause metadata/logs relating to both the uploader and downloader of the file the report concerns that would have been discarded to be kept beyond standard retention period(s)
2. Will assist in monitoring for widespread (presumably automated) abuse of the service that may have evaded other measures.
3. May allow further measures intended specifically to frustrate further abuse of the service by the individual(s) responsible
4. As they are based on "claims" of abuse careful consideration should be given to what is appropriate as the reports themselves may be the malicious action

### 'detailed' report
I also propose that, for certain categories of report and after ensuring we have the users **informed consent** it will also eventually be possible to opt-in to a 'detailed report'
1. No compromises on informed consent, this would require the consequences to be explained in detail (specifically the filename and hashes more than anything else)
2. for which metadata only available to the client could be gathered and included in addition to the data from a standard report i.e
2.1 Filename
2.2 Content Type claimed by sender
2.3 Content type detected by receiver (content type sniffing?)
2.2.1 Format specific parsers? (ie list the files inside a zip archive)
2.2 Hash(s) (for checking against malwareDB's)
3. As the file may have triggered the users anti-virus software, it may be nessisary to retain the file data in localStorage until it either "times out" or the tab is closed (asking the user to retrieve the file from quarantine to "open" it again would not be smart) or calculate this metadata before discarding it.
4. This is still only a "claim" of abuse
5. While intended for internal use only, this may be able to provide, carefully redacted and summarised, threat data to 3rd parties?

### The encryption key
I have decided its probably a bad idea, but I have also given consideration to a "full report" with the aim of converting the users "claim" that someone (perhaps themselves, using the target of the reports internet connection) uploaded a file breaching the TOS to a "fact" (that a file with that checksum was actually uploaded). 
1. It would require the decryption key
2. I think this could be very damaging to user trust, while its possible for a malicious server to "steal" the key its to easy to criticise Send for not being secure if it can actually do it by design. Its certainly very distasteful to myself even if a duplicate of the file could be found with the hashes
3. Some content may actually be unlawful to poses, receiving the decryption key could be risky (legal perspective?) even if it was encrypted (wrapped) using a public key to prevent decryption (access) by anyone not holding the private key (as i doubt the law cares to make much of a distinction, in most jurisdictions)

**Closed** 2019-01-03 21:07 UTC
Labels: needs:product
