### ISSUE TITLE
[Enhancement] The uploaded files should be sorted depending on the upload/expiring time

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/send#215] opened 2017-07-18 13:44 UTC
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.dev.mozaws.net/" page.
2. Upload five files with different names at a one minute interval (eg: file1 through file5, to help the issue stand out).
3. After uploading the files navigate to "https://send.dev.mozaws.net/" page.
4. Observe the order in which the files are displayed.

[Expected result]:
- The uploaded files are sorted depending on the upload/expiring time.

[Actual results]:
- The uploaded files are displayed in a seemingly random order.

[Notes]:
- Here is a screen shot of the issue:
![send_issue](https://user-images.githubusercontent.com/20083658/28320076-5063d206-6bd8-11e7-9b25-2e0d54014ea7.png)

**Comment by pdehaan** [comment] 2017-07-18 15:55
Duplicate of #155?

**Closed** 2017-07-19 08:45 UTC
