### ISSUE TITLE
Home screen icon is blurry

### ISSUE THREAD

**Issue by adamopenweb** [mozilla/send#558] opened 2017-09-08 17:39 UTC
Minor issue. When adding to home screen on Android, the icon is kind of blurry.

STR:
1. Open Firefox for Android
2. Navigate to https://send.firefox.com
3. Go to the Firefox Menu, then Page, then Add to Home Screen

Expected Result:
Icon is high res

Actual Result:
Icon is low res (blurry)

(Loving this experiment btw)

**Comment by ehuggett** [comment] 2017-09-09 14:58
Its not as sharp as it could be for the "tile size" of my home screen, the edges also appear slightly clipped?

send.firefox.com offers two icon files, a 16x16px image with a white background and a 32x32px png with a transparent background. I assume we're both ended up with the transparent logo on our home screens? (I used a Firefox nightly)

note: the 16x16px favicon was removed in 53e8229 and is not available from send.dev.mozaws.net

**Comment by sevaan** [comment] 2017-09-14 18:24
It looks like the actual asset is blurry, probably due to it's size: https://send.firefox.com/favicon-32x32.48de2a43.png

According to [some research](http://www.emergeinteractive.com/insights/detail/The-Essentials-of-FavIcons-in-2017), a 32x32 icon just isn't good enough for the purposes of desktop/homescreen shortcuts. It turns out you need 13 different sizes to cover most cases.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/473531/30446762-144ea964-9958-11e7-99d2-6ecc678caf36.png">

[You can find these icons sizes zipped up here.](https://github.com/mozilla/send/files/1304057/send.favicons.zip)

**Comment by ehuggett** [comment] 2017-09-14 23:40
Is send_logo.svg the source of ultimate truth for the logo? 🐵  

- According the to svg data the send logo should be `#3E3D40` but i see `#4f4e51` in favicon-228.png?
- The edges of the cloud appear a little clipped/flat, but my exports are the same, this seems to be as simple as we can't show a nice curve at these resolutions. Its a real shame we can't just use the svg for the favicon http://caniuse.com/#feat=link-icon-svg

Dimensions
- This image (svg imported and scaled to 228x205, place centred on a 228x228 canvas by **GIMP**) shows both with favicon-228.png coloured to blue and send_logo.svg to green (overlaps are darker).
![send_logo_diff_multiply](https://user-images.githubusercontent.com/8090731/30459256-79b97b04-99a7-11e7-97c0-85c34b82132f.png)


- SVG file exported by **Inkscape** (canvas _not_ resized to 228x228, image is 228x205)
![send_logo svg2](https://user-images.githubusercontent.com/8090731/30460139-e3193d0a-99ac-11e7-99d2-0f4435f16e5b.png)
- favicon-228.png from the zip file
![favicon-228](https://user-images.githubusercontent.com/8090731/30459584-87f50c54-99a9-11e7-926e-8f0c90074939.png)

I maintained the aspect ratio while importing/scaling the image to 228x228, but I don't think this accounts for the difference in stroke width?

I did try a favicon generator but it failed to render the chain in the SVG correctly, were these also produced automatically? I had started looking at options for exporting the svg file to the various sizes as part of `npm run build` (I thought it would be nice to avoid maintaining a set of favicons manually, even windows metro tiles want their own... )

**Comment by sevaan** [comment] 2017-09-15 01:00
Great catch! I just pulled the logo out of one of our Sketch files and used that, but now that I compare it to other sketch files, the stroke has been changed. I must have turned off the borders of the shapes at some point in the past.

[Here is a re-export of all the icons.](http://i.sevaan.com/090E0H34270U)

I manually created these, but recorded a Photoshop action while doing it, so it will be quick in the future.

**Comment by ehuggett** [comment] 2017-09-15 14:04
Thanks, but I just happened to notice while looking at the round edges of the cloud.

The new favicon-228 looks good. I think the differences are now deliberate choices, the logo in the svg not actually being centered probably accounts for all them.

![send_logo_diff_newzip](https://user-images.githubusercontent.com/8090731/30485830-85900df6-9a26-11e7-9275-e5b259af604d.png)

(I'll see what I can do about centring the original svg logo)

**Comment by ehuggett** [comment] 2017-09-15 15:03
Adding `transform="translate(-0.231,0.11948695)"` to the `g` element appears to be the most significant difference after trying this with inkscape, but the xml it produces is quite verbose (and for a different version of the standard?). I simply added the transform to the current svg with a text editor

note: I left inkscape to determine the centre of the logo, its the literal half heigh half width point centred on the defined canvas size

https://github.com/ehuggett/send/commits/svg-logo
before
![send_logo svg](https://user-images.githubusercontent.com/8090731/30488393-188a8166-9a2e-11e7-8f56-aa4a9bfe1237.png)
after
![send_logo-cen svg](https://user-images.githubusercontent.com/8090731/30488392-187de410-9a2e-11e7-84a5-34b941b2ff6d.png)
(the difference is barely noticeable even at 10x, green background added after export to show image edges)

A proper fix would be to change all of the coordinates rather than hacking it up with a transform, but I can make a PR it if its "good enough"

**Comment by sevaan** [comment] 2017-09-15 16:25
I think that looks great. Please go ahead and make a PR, thanks so much!

**Comment by ericawright** [comment] 2017-10-04 20:37
Fixed by #571

**Comment by ehuggett** [comment] 2017-10-04 21:41
The issue might not be resolved? @sevaan did you mean to commit something (your favicons?) or did i imply i would work work out how to use them

Either I'm confused or i've caused some confusion, but either way i think it would have been avoided if i had opened a separate issue. Apologies @ericawright

**Comment by ericawright** [comment] 2017-10-04 21:47
that's okay, my bad

**Comment by sevaan** [comment] 2017-10-05 20:25
[Cleaner export of icons for Erica.](http://i.sevaan.com/260w3T07162c)

**Closed** 2017-10-06 18:40 UTC
Labels: ready

**Comment by SoftVision-CiprianMuresan** [comment] 2017-10-09 11:38
The issue is no longer reproducbile if I add the Dev page to the homescreen.
