### ISSUE TITLE
Object.entries polyfill for older browsers?

### ISSUE THREAD

**Issue by jessicah** [mozilla/send#426] opened 2017-08-04 07:02 UTC
On Haiku, with both WebPositive & QupZilla, I'm seeing the error 'Object.entries' is not a function. We don't have more modern browsers than these, and it seems LocalStorage and Crypto APIs are both supported, so in theory it should work in these browsers.

**Comment by pdehaan** [comment] 2017-08-04 07:32
Thanks @jessicah,

I believe this is a duplicate of #395, which was fixed by PR #396 (add **babel-polyfill**).

We're hoping to get a new version deployed to production as soon as possible.

**Comment by wresuolc** [comment] 2017-08-04 15:56
duplicate of #395

**Closed by wresuolc** 2017-08-04 15:56 UTC
