### ISSUE TITLE
Need a meta description on the site

### ISSUE THREAD

**Issue by sevaan** [mozilla/send#371] opened 2017-08-01 16:01 UTC
Just saw the Google result for Firefox Send and the description could use a little work. Maybe there is some SEO we could apply here.

<img width="354" alt="screen shot 2017-08-01 at 11 55 08 am" src="https://user-images.githubusercontent.com/473531/28834730-1d144302-76b1-11e7-9671-938d9cf74b5b.png">

**Comment by pdehaan** [comment] 2017-08-01 16:22
This will probably be fixed along with #153's metadata work.

**Comment by wresuolc** [comment] 2017-08-02 16:01
duplicate of #153

**Closed by wresuolc** 2017-08-02 16:01 UTC
