### ISSUE TITLE
web client issue on loading : blanck screen 

### ISSUE THREAD

**Issue by lucasverra** [mozilla/send#1391] opened 2019-09-06 09:14 UTC
here it is on latest firefox macOs

![image](https://user-images.githubusercontent.com/11323803/64416443-7bf7fe80-d097-11e9-871a-a8166ea34795.png)

**Comment by NoUsername** [comment] 2019-09-06 11:01
Same on Windows 10 with Firefox Developer Edition 70.0b3 (64-bit)

**Comment by lucasverra** [comment] 2019-09-06 11:08
seems fixed now but will let contributors to close

**Comment by gcp** [comment] 2019-09-06 14:50
I guess this might be the same as https://github.com/mozilla/send/issues/1392.

**Comment by gcp** [comment] 2019-09-06 14:51
And probably #1390

**Comment by dannycoates** [comment] 2019-09-06 16:39
Thanks for the reports everyone. closing as a duplicate of #1390

**Closed by dannycoates** 2019-09-06 16:39 UTC
