### ISSUE TITLE
[Intermittent]Download progress is not correctly displayed

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/send#735] opened 2018-01-25 14:55 UTC
[Notes]:
- This issue is intermittent, you might need to repeat several times steps 3 & 4 to encounter it.
- You can encounter this issue easier after changing the number of downloads, but it also occurs intermittently without making this change.
- This issue is reproducible with large or small files.

[Affected versions]:
- Firefox  57.0.4 and up
- Firefox Send dev server

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Open Nightly browser and navigate to https://send.dev.mozaws.net
2. Upload a file and change the number of downloads.
3. Copy the download link and access it.
4. Click the "Download" button and observe the download progress.

[Expected result]:
- The download progress is correctly displayed.

[Actual result]:
- The download progress is not correctly displayed: it goes forward and only afterwards  comes back and continues its progress until the download is complete.

[Additional notes]:
- Here is a screen recording of this issue:
![progress bar - send](https://user-images.githubusercontent.com/31244235/35394054-63f8f5aa-01ef-11e8-91fb-6a5359a0c2dc.gif)

**Comment by dannycoates** [comment] 2018-01-25 20:08
weird!

**Comment by dannycoates** [comment] 2018-01-31 17:55
@himanish-star can you reproduce this bug? Logging the raw progress values from the `progress` event might help debug what's happening. There might be a simple fix but it'd be nice to see if we can understand why it's happening too.

**Comment by himanish-star** [comment] 2018-01-31 17:57
Yeah sure!

**Comment by himanish-star** [comment] 2018-01-31 18:10
danny, please give me some time for this. I'll definitely look into this tomorrow morning

**Comment by dannycoates** [comment] 2018-01-31 18:13
@himanish-star take all the time you need on this one 😉 (It's not "due" until Feb. 15)

**Comment by himanish-star** [comment] 2018-02-02 01:33
I was able to reproduce this issue and when I logged the `progress ratio` then I found out that first we get ratio as 0 then 1 and then it progresses normally and reaches to 1. So now I'm quite sure that this is what is causing the problem. Some relevant screenshots are give below
![screenshot from 2018-02-02 06-44-28](https://user-images.githubusercontent.com/30361728/35712209-ed7401ce-07e6-11e8-95cb-a0995ddfb824.png)
![senddata2](https://user-images.githubusercontent.com/30361728/35712211-eda963b4-07e6-11e8-8e78-2b839e72ae56.png)
![sendissuedownload](https://user-images.githubusercontent.com/30361728/35712212-edebba70-07e6-11e8-9c95-45f9ee382552.png)

**Comment by himanish-star** [comment] 2018-02-02 02:10
And one more thing I noticed was that initially the `event` which is received from `xhr.onprogress` had `event.loaded and event.total` as `12` which I have shown in this pic below and the same thing was also seen in all the downloads that I attempted. So shall I try and put a condition or something like that and try to fix it
![screenshot from 2018-02-02 07-36-41](https://user-images.githubusercontent.com/30361728/35713180-ebc5e5b8-07eb-11e8-8b4e-cc8bc36fb627.png)

**Comment by dannycoates** [comment] 2018-02-02 07:12
I don't know where the `12` comes from. I've not been able to reproduce it. Does Chrome do it as well?

**Comment by himanish-star** [comment] 2018-02-02 07:34
Yes chrome too!
![image](https://user-images.githubusercontent.com/30361728/35721753-8350fc1a-0819-11e8-8f9a-9e0b8c0e0c6b.png)

**Comment by dannycoates** [comment] 2018-02-02 17:56
It would be nice to know where that first event is coming from (especially since I can't repro on my mac) but I think we can work around it without knowing. In the progress event handler in `api.js` we could just ignore the first event and not send it up the chain.

**Comment by himanish-star** [comment] 2018-02-05 18:52
@dannycoates, I think the issue is now fixed. I was running an outdated code. I just now updated my code and I can't reproduce it any longer

**Comment by dannycoates** [comment] 2018-02-05 19:10
Awesome! Thanks for digging in to this @himanish-star

**Closed by dannycoates** 2018-02-05 19:10 UTC

**Comment by Softvision-CristinaBadescu** [comment] 2018-02-08 16:50
This issue is no longer reproducible using https://send.dev.mozaws.net/, on latest Nightly build 60.0a1 (2018-02-08), on Windows 10x64, Mac 10.12.6 and Arch Linux 4.12.
