### ISSUE TITLE
Muliple download option 

### ISSUE THREAD

**Issue by abinabrahamanchery** [mozilla/send#544] opened 2017-08-28 09:07 UTC
There should be an option to send multiple download links 
currently the link is valid only for 24 hours or Only 1 Download (which ever comes first) 
make the link active for 24 and multiple download option instead of one download option

**Comment by ehuggett** [comment] 2017-08-28 09:29
duplicate?/related https://github.com/mozilla/send/issues/420 https://github.com/mozilla/send/issues/98 https://github.com/mozilla/send/issues/525

**Comment by pdehaan** [comment] 2017-08-28 16:13
Yep, thanks @ehuggett!

Closing as duplicate of previously mentioned bugs.

**Closed by pdehaan** 2017-08-28 16:13 UTC
