### ISSUE TITLE
Add count remaining to the homepage file list

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#655] opened 2017-12-04 18:46 UTC

**Comment by himanish-star** [comment] 2017-12-23 03:28
@johngruen , on it

**Comment by himanish-star** [comment] 2017-12-23 05:40
@sevaan , @johngruen aren't #661 and this issue the same

**Comment by shikhar-scs** [comment] 2017-12-23 05:40
I guess this issue gets covered by PR #681

**Comment by dannycoates** [comment] 2018-01-19 23:08
duplicate of #661

**Closed by dannycoates** 2018-01-19 23:08 UTC
