### ISSUE TITLE
UI does not respond when a large file is dropped in

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#273] opened 2017-07-21 10:30 UTC
## STR

Drag in a large file and drop it

## Expected
Some kind of immediate indication that your file has been added

## Actual
Hover state persists on drag/drop box, and page feels frozen until redirect to uploading screen

@chenmorpheus, could you guys come up with something here?

**Comment by dannycoates** [comment] 2017-07-21 16:08
duplicate of #128 

My current plan for this is to immediately switch to the progress screen but change the label text from just "Uploading File" to a series of labels, one for each phase, "Importing File" -> "Verifying File" -> "Encrypting File" -> "Uploading File"

**Closed** 2017-07-21 16:08 UTC

**Comment by ChenMorpheus** [comment] 2017-07-24 03:13
Thanks Danny! That's exactly the solution I thought too!!
