### ISSUE TITLE
The "Try Firefox Send" link cancels the download

### ISSUE THREAD

**Issue by Dynom** [mozilla/send#407] opened 2017-08-03 09:24 UTC
On a download page, when a download is in progress, navigating away from the page cancels the link and the download. As an improvement there should be as few as possible triggers that cancel the download.

It happend to me when I clicked "Try Firefox Send" while waiting for a download to finish.

Perhaps opening links in a new window might be a quick fix?

Possibly related to https://github.com/mozilla/send/issues/347 and https://github.com/mozilla/send/issues/401

**Comment by pdehaan** [comment] 2017-08-03 15:24
I think this is a duplicate of #398 and fixed in #400 (which has been fixed in Git, but not deployed to production yet).

@dannycoates Not sure if we want to do a production deploy of v1.0.3 today (since it's not Friday and we fixed a few issues from Sentry, etc).

**Comment by dannycoates** [comment] 2017-08-03 21:57
Thanks for reporting. I'm closing as a dup of #398

**Closed by dannycoates** 2017-08-03 21:57 UTC
