### ISSUE TITLE
Check Russian language localization

### ISSUE THREAD

**Issue by sevaan** [mozilla/send#555] opened 2017-09-06 20:40 UTC
Just going through survey feedback and saw this one: 

**просрачиваются на русском это звучит двусмысленно )))**

Which in Google Translate reads: 
**they are skewed in Russian, this sounds ambiguous)))**

How do we check if it is localized correctly?

**Comment by flodolo** [comment] 2017-09-07 06:52
You need to identify another Russian speaker…

Honestly, as it stands the issue is not actionable, we need something more detailed to do anything, even get back to localizers.

**Comment by TemaSM** [comment] 2017-09-07 09:11
Native Russian speaker & Node.js dev already arrived 👌 
Will send PR with fixes for :ru: locale very soon

@sevaan @pdehaan @flodolo & other contributors, thank you guys for creating awesome Fiefox Send service, keep going!

**Comment by flodolo** [comment] 2017-09-07 09:15
> Native Russian speaker & Node.js dev already arrived 👌

Great! CC @unghost and @BychekRU

Ideally we would take corrections via Pontoon, so they're correctly attributed, a PR would work too
https://pontoon.mozilla.org/ru/test-pilot-firefox-send/

**Comment by BychekRU** [comment] 2017-09-11 18:11
@sevaan @TemaSM Thank you very much for indentifying problems with translations. Fixes were submitted through Pontoon.
Also we use "Загрузить" instead of "Скачать". You can check your glossary [https://wiki.mozilla.org/L10n:Teams:ru:Words](https://wiki.mozilla.org/L10n:Teams:ru:Words)

**Comment by sevaan** [comment] 2017-09-12 18:08
One more comment from the survey. Was this resolved as well?

> In russian version when the link is dead it's written "Это ссылка просрочена или никогда не существовала!". Bad spellling, should be "Эта ссылка...."

**Comment by TemaSM** [comment] 2017-09-12 18:39
@sevaan, yep info from feedback resolved, but there is one weird thing:
![image](https://user-images.githubusercontent.com/5501615/30342268-ee2ae1e6-9801-11e7-82e7-a298f526b15f.png)
How about to truncate label for URL copying and simply add title-like caption on button hover?
or
@BychekRU how do you think, is short form "Истекает" better than "Срок действия истекает через"?

**Comment by johngruen** [comment] 2017-09-13 18:04
@flod, @sevaan is filing a separate issue to deal with the above comment. can we close this?

**Closed by johngruen** 2017-09-13 18:04 UTC
Labels: l10n

**Comment by BychekRU** [comment] 2017-09-16 13:08
@TemaSM Sorry for the delay. I don't think that just simply "Истекает" will be better than "Срок действия истекает через". May be "Срок хранения"?
