### ISSUE TITLE
p2p mode

### ISSUE THREAD

**Issue by hbakhtiyor** [mozilla/send#553] opened 2017-09-04 13:12 UTC
would be nice to add p2p option too,

**Comment by ehuggett** [comment] 2017-09-04 14:33
There seem to be plenty of working examples for this (in no particular order, only from the first page of search results)

https://github.com/cowbell/sharedrop / https://www.sharedrop.io/
https://github.com/KodeKraftwerk/reepio / https://www.reep.io/
https://github.com/kern/filepizza / https://file.pizza/

If we kept the file encryption (I didn't look closely, but I believe all of the examples rely only upon transport encryption?) the Send server could become an optional peer (for when direct connections cannot be established) or even a seeder (in the BitTorrent sense) if the uploader will not be available at the time the downloader wants the file.

https://github.com/webtorrent/webtorrent/ / https://instant.io/

**Comment by wresuolc** [comment] 2017-09-06 17:41
duplicate of #424

**Closed by wresuolc** 2017-09-06 17:41 UTC
